---
name: "build macOS-10.15"
on: push
jobs:
  build_macos:
    runs-on: macOS-10.15
    steps:
      # - name: Checkout repository
      #   uses: minvws/nl-covid19-notification-app-ios@master
      - name: ciprep
        uses: ./tools/scripts/ci/010_ciprep
      - name: cibuild
        uses: ./tools/scripts/ci/030_cibuild
      - name: citest
        uses: ./tools/scripts/ci/050_citest
