---
name: "build macOS-10.15"
on: push
jobs:
  build_macos:
    name: build_macos_1015
    runs-on: macOS-10.15
    steps:
      - uses: minvws/nl-covid19-notification-app-ios@master
        name: Check out repository master branch
        with:
          fetch-depth: 5
      - uses: ./tools/scripts/ci/010_ciprep
        name: ciprep
      - uses: ./tools/scripts/ci/030_cibuild
        name: cibuild
      - uses: ./tools/scripts/ci/050_citest
        name: citest
